### ISSUE TITLE
How do we start testing?

### ISSUE THREAD

**Issue by eddieantonio** [JSMaika/intficpy#1]
Hello! 👋

I'm Eddie from EdmontonPy. How do we help you testing this? Will you be doing automated testing, or is it just play testing?

**Comment by JSMaika** [comment]
Hi. There are two main types of testing that I need:
The first is playtesting for the demo game (starting in about 4-6 weeks).
Secondly, I need people to try building games using IntFicPy.
I'm not entirely sure how to approach automated testing for this project, but if you have an idea I'd love to hear about it.

**Comment by eddieantonio** [comment]
I think right now, I'm more interested in play testing, but we'll see.

For automated testing, you may need to do a bit of refactoring. I like using [`py.test`](https://docs.pytest.org/en/latest/), though the current directory structure [needs to be changed](https://docs.pytest.org/en/latest/goodpractices.html?highlight=integration#choosing-a-test-layout-import-rules) to make it work smoothly. Test could be sanity checks (I can see through any transparent thing), and when you do have play testers and they find bugs, that's a good time to write a test, to trigger the bug, then you fix the bug, and the test passes.

**Comment by JSMaika** [comment]
Thanks. I'll look into that. If you want, I can contact you when beta testing for the demo game starts, and I'll send you the game if you're still interested.
