### ISSUE TITLE
Text Not Readable

### ISSUE THREAD

**Issue by cibersheep** [JSMaika/intficpy#3]
Running the test game shows text like this:

![imatge](https://user-images.githubusercontent.com/6640041/66016434-f4a37c80-e4d6-11e9-889e-fadcbee887eb.png)

Thanks for your work

**Comment by JSMaika** [comment]
Hi. I wasn't able to replicate the issue from my local machine, but I suspect it's caused by the lack of a set text colour in the default style. I've set it to black now. If you have the time, I would appreciate if you could confirm whether or not this fixed your issue.

Thanks a bunch!

**Comment by cibersheep** [comment]
Perrrrrrrfect
![imatge](https://user-images.githubusercontent.com/6640041/66207835-1574f900-e6b4-11e9-93c2-cb11174c8e8b.png)

Thaaaaank you. I must have a weird theme :D
